repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^sdks/opik_optimizer
      - id: end-of-file-fixer
        files: ^sdks/opik_optimizer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes]
        files: ^sdks/opik_optimizer
      - id: ruff-format
        files: ^sdks/opik_optimizer

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        files: ^sdks/opik_optimizer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^sdks/opik_optimizer
        exclude: '(sdks/opik_optimizer/src/opik_optimizer/mipro_optimizer/)'
        # `exclude` option will work only from here.
        # The rest of mypy configuration can be moved to pyproject.toml
        args: [--config-file, sdks/opik_optimizer/pyproject.toml, --ignore-missing-imports]
        additional_dependencies: [types-requests]
