name: comet-llm-eval

services:
  db-app:
    image: mysql
    hostname: db-app
    environment:
      MYSQL_ROOT_PASSWORD: comet
      MYSQL_DATABASE: comet_llm_eval
      MYSQL_USER: comet
      MYSQL_PASSWORD: comet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      timeout: 1s
      interval: 1s
      retries: 300
    ports:
      - "3306:3306"

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"

  backend:
    hostname: backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPIK_VERSION: latest
    environment:
      DOCKER_BUILDKIT: 1
      STATE_DB_URL: jdbc:mysql://db-app:3306/comet_llm_eval?createDatabaseIfNotExist=true&rewriteBatchedStatements=true
      STATE_DB_DATABASE_NAME: comet_llm_eval
      STATE_DB_USER: comet
      STATE_DB_PASS: comet
      ANALYTICS_DB_MIGRATIONS_URL: jdbc:clickhouse://db-app-analytics:8123/comet_llm_eval
      ANALYTICS_DB_MIGRATIONS_USER: comet
      ANALYTICS_DB_MIGRATIONS_PASS: comet
      ANALYTICS_DB_PROTOCOL: HTTP
      ANALYTICS_DB_HOST: db-app-analytics
      ANALYTICS_DB_PORT: 8123
      ANALYTICS_DB_USERNAME: comet
      ANALYTICS_DB_PASS: comet
      ANALYTICS_DB_DATABASE_NAME: comet_llm_eval
      REDIS_URL: redis://redis:6379
      JAVA_OPTS: "-Dliquibase.propertySubstitutionEnabled=true"
      OPIK_OTEL_SDK_ENABLED: true
      OTEL_VERSION: 2.12.0
      OTEL_EXPORTER_OTLP_COMPRESSION: gzip
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_PROPAGATORS: "tracecontext,baggage,b3"
      OTEL_EXPERIMENTAL_EXPORTER_OTLP_RETRY_ENABLED: true
      OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
      OTEL_EXPERIMENTAL_RESOURCE_DISABLED_KEYS: process.command_args
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: delta
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net
      OTEL_EXPORTER_OTLP_HEADERS: api-key=e37fbbc9bda80b7703064ff3505ec6f1FFFFNRAL
      ENABLE_VIRTUAL_THREADS: true
      OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT: 4095
    ports:
      - "8080:8080"
      - "3003:3003"
    depends_on:
      db-app:
        condition: service_healthy
      db-app-analytics:
        condition: service_healthy

  frontend:
    image: comet-llm-eval-frontend
    hostname: frontend
    build:
      context: ../opik-frontend/
      dockerfile: ../opik-frontend/Dockerfile
      args:
        OPIK_VERSION: latest
    environment:
      VITE_BASE_API_URL: http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started

  db-app-analytics:
    image: clickhouse/clickhouse-server:24.8.4.13-alpine
    hostname: db-app-analytics
    environment:
      CLICKHOUSE_DB: comet_llm_eval
      CLICKHOUSE_USER: comet
      CLICKHOUSE_PASSWORD: comet
      # Enables SQL-driven Access Control and Account Management:
      # https://clickhouse.com/docs/en/operations/access-rights#enabling-access-control
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123" # HTTP default port
      - "9000:9000" # Native Protocol port
    volumes: # Mounted on your $HOME folder
      - ~/clickhouse/data:/var/lib/clickhouse/
      - ~/clickhouse/logs:/var/log/clickhouse-server/
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8123/ping" ]
      interval: 1s
      timeout: 1s
      retries: 300
networks:
  default: