---
name: 🤖 Auto Assign Copilot Reviewer for Bounty Claims

"on":
  pull_request:
    types: [opened, labeled]

jobs:
  assign_copilot_reviewer:
    name: Assign GitHub Copilot as Reviewer
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, '🙋 Bounty claim')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Request GitHub Copilot review
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"

          echo "Requesting GitHub Copilot review for bounty claim PR #$PR_NUMBER"

          # Add github-copilot[bot] as a reviewer
          gh pr edit "$PR_NUMBER" --add-reviewer "github-copilot[bot]" \
            --repo "${{ github.repository }}" || true

          echo "Successfully requested GitHub Copilot review for PR #$PR_NUMBER"

      - name: Add comment about Copilot review
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # Add a comment explaining the automatic Copilot review
          gh pr comment "$PR_NUMBER" --repo "${{ github.repository }}" \
            --body "🤖 **GitHub Copilot has been automatically assigned as \
            a reviewer** for this bounty claim PR. Copilot will provide an \
            initial code review to help ensure code quality and security \
            standards."