name: Trigger Test Environment Deployment
run-name: ${{ github.event.label.name == 'test-environment' && format('Trigger Test Environment Deployment for PR {0} by {1}', github.event.number, github.actor) || 'Test Environment Not Triggered' }}

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:

  other-labels:
    if: github.event.label.name != 'test-environment'
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: |
          echo "Skipping deployment of test environment for this PR"

  notify-started:
    if: github.event.label.name == 'test-environment'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR - Deployment Started
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: Number('${{ github.event.number }}'),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔄 **Test environment deployment started**
              
              Building images for PR #${{ github.event.number }}...
              
              You can monitor the build progress [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).`
            });

  build-apps:
    if: github.event.label.name == 'test-environment'
    needs:
      - notify-started
    uses: ./.github/workflows/build_apps.yml
    secrets: inherit
    with:
      version: ""
      is_release: false
      build_guardrails: false
      ref: ${{ github.event.pull_request.head.ref }}

  trigger_deployment:
    if: github.event.label.name == 'test-environment'
    needs:
      - build-apps
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment via repository dispatch
        uses: actions/github-script@v7
        env:
          VERSION_NAME: ${{ needs.build-apps.outputs.version }}
        with:
          github-token: ${{ secrets.DEPLOYMENT_TRIGGER_TOKEN }}
          script: |
            const response = await github.rest.repos.createDispatchEvent({
              owner: 'comet-ml',
              repo: 'comet-deployment',
              event_type: 'deploy-opik-test-env',
              client_payload: {
                pr_number: '${{ github.event.number }}',
                version_name: process.env.VERSION_NAME
              }
            });
            
            console.log('Repository dispatch sent:', response.status);

      - name: Wait for deployment to be available
        shell: bash
        run: |
          URL="https://pr-${{ github.event.number }}.dev.comet.com/api/health-check"
          TIMEOUT=600  # 10 minutes in seconds
          INTERVAL=10  # Check every 10 seconds
          # Initial delay to allow deployment to start before health checks
          INITIAL_DELAY=60
          ELAPSED=0
          
          echo "Waiting for deployment to be available at: $URL"
          echo "Timeout: ${TIMEOUT} seconds (10 minutes)"
          sleep $INITIAL_DELAY
          
          while [ $ELAPSED -lt $TIMEOUT ]; do
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
            
            if [ "$HTTP_CODE" = "200" ]; then
              echo "✅ Deployment is available! Health check returned 200"
              exit 0
            fi
            
            echo "⏳ Waiting... (${ELAPSED}s elapsed, HTTP code: ${HTTP_CODE})"
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done
          
          echo "❌ Timeout: Deployment did not become available within 10 minutes"
          exit 1

      - name: Comment on PR - Deployment Available
        if: success()
        uses: actions/github-script@v7
        env:
          VERSION_NAME: ${{ needs.build-apps.outputs.version }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: Number('${{ github.event.number }}'),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Test environment is now available!**

              ### Access Information
              - **URL:** https://pr-${{ github.event.number }}.dev.comet.com
              - **Namespace:** pr-${{ github.event.number }}
              - **Version:** ${process.env.VERSION_NAME}
              
              The deployment has been verified and is ready to use.`
            });

      - name: Handle deployment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: Number('${{ github.event.number }}'),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **Test environment deployment failed or timed out**
              
              The deployment did not become available within 10 minutes. Please check the [deployment logs](https://github.com/comet-ml/comet-deployment/actions/workflows/deploy_opik_adhoc_env.yaml) for more details.`
            });
